#!/usr/bin/env bash
# Regenerate dist/ from palette.json. Run it after editing the palette and commit both
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
src="$here/palette.json"
out="$here/dist"

command -v jq >/dev/null || {
  echo "generate.sh: jq is required" >&2
  exit 1
}

mkdir -p "$out"

# Flatten to "group name hex" lines — every format below is built from these
flat() {
  jq -r 'to_entries[] | select(.key != "meta" and .key != "base16") | .key as $g
    | .value | to_entries[] | "\($g) \(.key) \(.value.hex)"' "$src"
}

banner="Generated by generate.sh from palette.json — do not edit"

# A camelCase name has to be respelled where the convention differs: kebab in CSS,
# SNAKE in a shell variable. This puts the separator in, the caller sets the case
hump() {
  local s="$1" sep="$2" out=""
  while [[ $s =~ ^([^A-Z]*)([A-Z])(.*)$ ]]; do
    out+="${BASH_REMATCH[1]}$sep${BASH_REMATCH[2]}"
    s="${BASH_REMATCH[3]}"
  done
  printf '%s' "$out$s"
}
kebab() {
  local s
  s="$(hump "$1" -)"
  printf '%s' "${s,,}"
}
snake() {
  local s
  s="$(hump "$1" _)"
  printf '%s' "${s^^}"
}

{
  echo "/* $banner */"
  echo ":root {"
  flat | while read -r _ name hex; do echo "  --ddlc-$(kebab "$name"): $hex;"; done
  echo "}"
} >"$out/palette.css"

{
  echo "# $banner"
  echo "{"
  flat | while read -r _ name hex; do echo "  $name = \"$hex\";"; done
  echo "}"
} >"$out/palette.nix"

{
  echo "# $banner"
  echo "# Source this from a shell script: . dist/palette.sh"
  flat | while read -r _ name hex; do echo "DDLC_$(snake "$name")='$hex'"; done
} >"$out/palette.sh"

# Hex without the leading # — hyprland, hyprlock and mako all want it that way
{
  echo "# $banner"
  flat | while read -r _ name hex; do echo "$name=${hex#\#}"; done
} >"$out/palette.env"

# base16 schemes, one file per variant. A bare "base0B" says nothing about where its colour came
# from, so every slot carries the palette key, how that key was arrived at and its own provenance
for variant in light dark; do
  {
    echo "# $banner"
    echo "system: \"base16\""
    echo "name: \"DDLC $variant\""
    echo "author: \"rokokol — colours by Team Salvato, measured off https://ddlc.moe/\""
    echo "variant: \"$variant\""
    echo "description: \"The Doki Doki Literature Club colours, read off the official site. Provenance per colour: https://github.com/rokokol/ddlc-palette/blob/master/palette.json\""
    echo "palette:"
    jq -r --arg v "$variant" '
      ([to_entries[] | select(.key != "meta" and .key != "base16") | .value | to_entries[]]
        | from_entries) as $c
      | .base16[$v] | to_entries[] | select(.key | startswith("base"))
      | "  \(.key): \"\($c[.value].hex)\" # \(.value) (\($c[.value].method)) — \($c[.value].source)"
    ' "$src"
  } >"$out/base16-ddlc-$variant.yaml"
done

# The app configs below name slots, so resolve them once per variant. $V picks the variant
declare -A slot
for variant in light dark; do
  while read -r key hex; do slot["$variant/$key"]="$hex"; done < <(
    jq -r --arg v "$variant" '
      ([to_entries[] | select(.key != "meta" and .key != "base16") | .value | to_entries[]]
        | from_entries) as $c
      | .base16[$v] | to_entries[] | select(.key | startswith("base"))
      | "\(.key) \($c[.value].hex)"
    ' "$src"
  )
done
s() { printf '%s' "${slot["$V/$1"]}"; }

for V in light dark; do

  # Slot for slot the mapping tinted-theming/tinted-kitty uses, with one departure: it grounds
  # the selection in base03, which leaves base05 on it at 1.65:1 here, so base02 carries it
  {
    echo "# $banner"
    echo "# vim:ft=kitty"
    echo "# Include this from kitty.conf: include kitty-ddlc-$V.conf"
    echo
    echo "background $(s base00)"
    echo "foreground $(s base05)"
    echo "selection_background $(s base02)"
    echo "selection_foreground $(s base05)"
    echo "cursor $(s base05)"
    echo "cursor_text_color $(s base00)"
    echo "url_color $(s base04)"
    echo "active_border_color $(s base03)"
    echo "inactive_border_color $(s base01)"
    echo "wayland_titlebar_color $(s base00)"
    echo "macos_titlebar_color $(s base00)"
    echo "active_tab_background $(s base00)"
    echo "active_tab_foreground $(s base05)"
    echo "inactive_tab_background $(s base01)"
    echo "inactive_tab_foreground $(s base04)"
    echo "tab_bar_background $(s base01)"
    echo
    for pair in "0 base00" "1 base08" "2 base0B" "3 base0A" "4 base0D" "5 base0E" "6 base0C" "7 base05" \
      "8 base02" "9 base08" "10 base0B" "11 base0A" "12 base0D" "13 base0E" "14 base0C" "15 base07" \
      "16 base09" "17 base0F" "18 base01" "19 base02" "20 base04" "21 base06"; do
      set -- $pair
      echo "color$1 $(s "$2")"
    done
  } >"$out/kitty-ddlc-$V.conf"

  # btop has no base16 template anywhere upstream, so this mapping is ours. Meters that carry no
  # scale are one colour — btop reads that as a start with an empty mid and end
  {
    echo "# $banner"
    echo "# Drop into ~/.config/btop/themes/ and select it with color_theme=\"ddlc-$V\""
    echo
    echo "theme[main_bg]=\"$(s base00)\""
    echo "theme[main_fg]=\"$(s base05)\""
    echo "theme[title]=\"$(s base06)\""
    echo "theme[hi_fg]=\"$(s base0A)\""
    echo "theme[selected_bg]=\"$(s base02)\""
    echo "theme[selected_fg]=\"$(s base06)\""
    echo "theme[inactive_fg]=\"$(s base03)\""
    echo "theme[graph_text]=\"$(s base04)\""
    echo "theme[meter_bg]=\"$(s base01)\""
    echo "theme[proc_misc]=\"$(s base0B)\""
    echo "theme[cpu_box]=\"$(s base0D)\""
    echo "theme[mem_box]=\"$(s base0B)\""
    echo "theme[net_box]=\"$(s base0E)\""
    echo "theme[proc_box]=\"$(s base0C)\""
    echo "theme[div_line]=\"$(s base03)\""
    # Load rises through the palette's warm accents: green, then yellow, then red
    for gradient in temp cpu process; do
      echo "theme[${gradient}_start]=\"$(s base0B)\""
      echo "theme[${gradient}_mid]=\"$(s base0A)\""
      echo "theme[${gradient}_end]=\"$(s base08)\""
    done
    for pair in "free base0B" "cached base0C" "available base0A" "used base08" "download base0D" "upload base0E"; do
      set -- $pair
      echo "theme[$1_start]=\"$(s "$2")\""
      echo "theme[$1_mid]=\"\""
      echo "theme[$1_end]=\"\""
    done
  } >"$out/btop-ddlc-$V.theme"

  # A colorscheme for plain vim and for nvim without a plugin. tinted-vim renders the same slots
  # into ten times the lines by carrying cterm fallbacks; this one asks for termguicolors instead
  {
    echo "\" $banner"
    echo "\" Drop into ~/.vim/colors/ or ~/.config/nvim/colors/ and :colorscheme ddlc-$V"
    echo "\" Needs a truecolour terminal: set termguicolors"
    echo
    echo "hi clear"
    echo "if exists(\"syntax_on\") | syntax reset | endif"
    echo "set background=$V"
    echo "let g:colors_name = \"ddlc-$V\""
    echo
    # group  fg  bg  gui — "-" is NONE, and a lone "" row breaks the file into sections
    while read -r group fg bg gui; do
      [ -z "$group" ] && { echo; continue; }
      [ "$fg" = "-" ] && fg=NONE || fg="$(s "$fg")"
      [ "$bg" = "-" ] && bg=NONE || bg="$(s "$bg")"
      echo "hi $group guifg=$fg guibg=$bg gui=${gui:-NONE}"
    done <<'GROUPS'
Normal          base05 base00
NonText         base03 -
EndOfBuffer     base03 -
Conceal         base0D -
LineNr          base04 base00
CursorLineNr    base06 base01
CursorLine      -      base01
CursorColumn    -      base01
ColorColumn     -      base01
SignColumn      base04 base00
FoldColumn      base0C base00
Folded          base03 base01
Visual          -      base02
VisualNOS       base08 -
Search          base01 base0A
IncSearch       base01 base09
CurSearch       base01 base09
MatchParen      -      base03
StatusLine      base04 base02
StatusLineNC    base03 base01
VertSplit       base02 -
WinSeparator    base02 -
TabLine         base03 base01
TabLineFill     base03 base01
TabLineSel      base0B base01
Pmenu           base05 base01
PmenuSel        base01 base05
PmenuSbar       -      base02
PmenuThumb      -      base07
WildMenu        base01 base05
Directory       base0D -
Title           base0D -      bold
Question        base0B -
MoreMsg         base0B -
ModeMsg         base0B -
WarningMsg      base08 -
ErrorMsg        base08 -
Error           base00 base08
Todo            base0A base01
SpecialKey      base03 -
Cursor          base00 base05
QuickFixLine    -      base01

Comment         base03 -      italic
Constant        base09 -
String          base0B -
Character       base08 -
Number          base09 -
Boolean         base09 -
Float           base09 -
Identifier      base08 -
Function        base0D -
Statement       base0E -
Conditional     base0E -
Repeat          base0E -
Label           base0A -
Operator        base05 -
Keyword         base0E -
Exception       base08 -
PreProc         base0A -
Include         base0D -
Define          base0E -
Macro           base08 -
PreCondit       base0A -
Type            base0A -
StorageClass    base0A -
Structure       base0E -
Typedef         base0A -
Special         base0C -
SpecialChar     base0F -
Tag             base0A -
Delimiter       base0F -
Debug           base08 -
Underlined      base08 -      underline
Ignore          base00 -

DiffAdd         base0B base01
DiffChange      base03 base01
DiffDelete      base08 base01
DiffText        base0D base01
SpellBad        -      -      undercurl
SpellLocal      -      -      undercurl
SpellCap        -      -      undercurl
SpellRare       -      -      undercurl
GROUPS
    echo
    echo "\" Neovim only — plain vim has no diagnostics and simply ignores these"
    while read -r group fg bg gui; do
      [ "$fg" = "-" ] && fg=NONE || fg="$(s "$fg")"
      [ "$bg" = "-" ] && bg=NONE || bg="$(s "$bg")"
      echo "hi $group guifg=$fg guibg=$bg gui=${gui:-NONE}"
    done <<'DIAGNOSTICS'
DiagnosticError base08 -
DiagnosticWarn  base09 -
DiagnosticInfo  base0D -
DiagnosticHint  base0C -
DiagnosticOk    base0B -
NormalFloat     base05 base01
FloatBorder     base03 base01
DIAGNOSTICS
  } >"$out/vim-ddlc-$V.vim"

done

# Swatch card for the README — SVG so the labels use the reader's own font
{
  cols=4
  sw=170
  sh=88
  n=$(flat | wc -l)
  rows=$(((n + cols - 1) / cols))
  echo "<!-- $banner -->"
  echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"$((cols * sw))\" height=\"$((rows * sh))\" viewBox=\"0 0 $((cols * sw)) $((rows * sh))\" font-family=\"ui-monospace, monospace\">"
  i=0
  while read -r _ name hex; do
    x=$(((i % cols) * sw))
    y=$(((i / cols) * sh))
    # Dark swatches need light text; luminance from the top two bits is enough here
    r=$((16#${hex:1:2}))
    g=$((16#${hex:3:2}))
    b=$((16#${hex:5:2}))
    lum=$(((r * 299 + g * 587 + b * 114) / 1000))
    fg="#111111"
    [[ $lum -lt 140 ]] && fg="#FFFFFF"
    echo "  <rect x=\"$x\" y=\"$y\" width=\"$sw\" height=\"$sh\" fill=\"$hex\"/>"
    echo "  <text x=\"$((x + 14))\" y=\"$((y + 36))\" fill=\"$fg\" font-size=\"17\">$name</text>"
    echo "  <text x=\"$((x + 14))\" y=\"$((y + 62))\" fill=\"$fg\" font-size=\"14\" opacity=\"0.75\">$hex</text>"
    i=$((i + 1))
  done < <(flat)
  echo "</svg>"
} >"$out/palette.svg"

echo "wrote $out/palette.{css,nix,sh,env,svg} and, per variant, $out/{base16-ddlc-VARIANT.yaml,kitty-ddlc-VARIANT.conf,btop-ddlc-VARIANT.theme,vim-ddlc-VARIANT.vim}"
