#!/usr/bin/env bash
# Regenerate dist/ from palette.json. Run it after editing the palette and commit both
set -euo pipefail

here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
src="$here/palette.json"
out="$here/dist"

command -v jq >/dev/null || {
  echo "generate.sh: jq is required" >&2
  exit 1
}

mkdir -p "$out"

# Flatten to "group name hex" lines — every format below is built from these
flat() {
  jq -r 'to_entries[] | select(.key != "meta" and .key != "base16") | .key as $g
    | .value | to_entries[] | "\($g) \(.key) \(.value.hex)"' "$src"
}

banner="Generated by generate.sh from palette.json — do not edit"

# A camelCase name has to be respelled where the convention differs: kebab in CSS,
# SNAKE in a shell variable. This puts the separator in, the caller sets the case
hump() {
  local s="$1" sep="$2" out=""
  while [[ $s =~ ^([^A-Z]*)([A-Z])(.*)$ ]]; do
    out+="${BASH_REMATCH[1]}$sep${BASH_REMATCH[2]}"
    s="${BASH_REMATCH[3]}"
  done
  printf '%s' "$out$s"
}
kebab() {
  local s
  s="$(hump "$1" -)"
  printf '%s' "${s,,}"
}
snake() {
  local s
  s="$(hump "$1" _)"
  printf '%s' "${s^^}"
}

{
  echo "/* $banner */"
  echo ":root {"
  flat | while read -r _ name hex; do echo "  --ddlc-$(kebab "$name"): $hex;"; done
  echo "}"
} >"$out/palette.css"

{
  echo "# $banner"
  echo "{"
  flat | while read -r _ name hex; do echo "  $name = \"$hex\";"; done
  echo "}"
} >"$out/palette.nix"

{
  echo "# $banner"
  echo "# Source this from a shell script: . dist/palette.sh"
  flat | while read -r _ name hex; do echo "DDLC_$(snake "$name")='$hex'"; done
} >"$out/palette.sh"

# Hex without the leading # — hyprland, hyprlock and mako all want it that way
{
  echo "# $banner"
  flat | while read -r _ name hex; do echo "$name=${hex#\#}"; done
} >"$out/palette.env"

# base16 schemes, one file per variant. A bare "base0B" says nothing about where its colour
# came from, so every slot carries the palette key and that entry's own provenance
for variant in light dark; do
  {
    echo "# $banner"
    echo "system: \"base16\""
    echo "name: \"DDLC $variant\""
    echo "author: \"rokokol — colours by Team Salvato, measured off https://ddlc.moe/\""
    echo "variant: \"$variant\""
    echo "description: \"The Doki Doki Literature Club colours, read off the official site. Provenance per colour: https://github.com/rokokol/ddlc-palette/blob/master/palette.json\""
    echo "palette:"
    jq -r --arg v "$variant" '
      ([to_entries[] | select(.key != "meta" and .key != "base16") | .value | to_entries[]]
        | from_entries) as $c
      | .base16[$v] | to_entries[] | select(.key | startswith("base"))
      | "  \(.key): \"\($c[.value].hex)\" # \(.value) — \($c[.value].source)"
    ' "$src"
  } >"$out/base16-ddlc-$variant.yaml"
done

# Swatch card for the README — SVG so the labels use the reader's own font
{
  cols=4
  sw=170
  sh=88
  n=$(flat | wc -l)
  rows=$(((n + cols - 1) / cols))
  echo "<!-- $banner -->"
  echo "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"$((cols * sw))\" height=\"$((rows * sh))\" viewBox=\"0 0 $((cols * sw)) $((rows * sh))\" font-family=\"ui-monospace, monospace\">"
  i=0
  while read -r _ name hex; do
    x=$(((i % cols) * sw))
    y=$(((i / cols) * sh))
    # Dark swatches need light text; luminance from the top two bits is enough here
    r=$((16#${hex:1:2}))
    g=$((16#${hex:3:2}))
    b=$((16#${hex:5:2}))
    lum=$(((r * 299 + g * 587 + b * 114) / 1000))
    fg="#111111"
    [[ $lum -lt 140 ]] && fg="#FFFFFF"
    echo "  <rect x=\"$x\" y=\"$y\" width=\"$sw\" height=\"$sh\" fill=\"${hex:0:7}\"/>"
    echo "  <text x=\"$((x + 14))\" y=\"$((y + 36))\" fill=\"$fg\" font-size=\"17\">$name</text>"
    echo "  <text x=\"$((x + 14))\" y=\"$((y + 62))\" fill=\"$fg\" font-size=\"14\" opacity=\"0.75\">$hex</text>"
    i=$((i + 1))
  done < <(flat)
  echo "</svg>"
} >"$out/palette.svg"

echo "wrote $out/palette.{css,nix,sh,env,svg} and $out/base16-ddlc-{light,dark}.yaml"
